[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"

[wandb]
run_name = "decay"
project_name = "vlm_debug_lr"
entity_name = "bsc_runs"
log_topk = false

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen3_2b"
output_dir = "/data/151-1/users/tockier/qwen_finetune/checkpoints_debug"

load_text_model = false
load_vision_model = false

save_steps = 100000

scheduler_type = "wsd"

total_steps = 50
warmup_steps = 10

wsd_decay_ratio = 0

bfloat16 = true
tp_size = 1
data_parallel = 'ddp'
compile = false

resume_checkpoint = true

[data]
data_path = "/data/151-1/datasets/synth_test_datasets/cap_pretrain"
seq_len = 2048

batch_size = 0
packing_buffer_size = 100
