[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"
run_name = "vlm_test"
project_name = "test"
entity_name = "bsc_runs"

train_llm = true
train_mlp = true
train_vit = false

[training]
model_dir = "/gpfs/scratch/ehpc391/cache/qwen3_2b/"
text_cache_dir =  "/gpfs/scratch/ehpc391/cache/qwen3_1_7b/"
output_dir = "/gpfs/scratch/ehpc543/qwen_finetune/vlm_large"

load_text_model = true

save_steps = 1000
total_steps = 10_000

scheduler_type = "cosine"
warmup_steps = 100
min_lr_ratio = 0.1

lr_llm = 0.00002
lr_mlp = 0.0001

data_parallel = 'ddp'
tp_size = 1

random_init_mlp = true

[data]
data_path = "/gpfs/scratch/ehpc543/FineVisionMax/full/"
seq_len = 8192

start_idx = 6000
end_idx = 9999