[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"

train_llm = true
train_mlp = true
train_vit = false

[wandb]
run_name = "test"
project_name = "mn5_onevision"
entity_name = "bsc_runs"

[training]
model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/qwen3vl_2b"
output_dir = "/gpfs/scratch/ehpc543/qwen_finetune/onevision_large_merger_start"

text_model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/qwen3_1_7b"
load_text_model = true

vision_model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/siglip2_large"
load_vision_model = true

save_steps = 500
total_steps = 50_000

scheduler_type = "wsd"
warmup_steps = 500
min_lr_ratio = 0.1

lr_llm = 0.000005
lr_mlp = 0.00001
lr_vit = 0.00001

data_parallel = 'ddp'
tp_size = 1

tpi_multiplier = 1
compile = true

ac_memory_budget = 0.0
clear_cache_vram = 50
debug_batch_stats = false

[data]
data_path = "/gpfs/scratch/ehpc543/onevision_instruct"
seq_len = 8192

packing_buffer_size = 1000
batch_size = 0