[model]
model_name = "Qwen/Qwen3-VL-4B-Instruct"

[wandb]
run_name = "test_4B_quad_node"
project_name = "bsc_8b"
entity_name = "bsc_runs"

[training]
model_name = "/gpfs/scratch/ehpc391/qwens/qwen3_4b/"
output_dir = "/gpfs/scratch/ehpc391/qwen_finetune/test_4b/"

save_steps = 500

total_steps = 1000

data_parallel = 'fsdp'
tp_size = 1

[data]
data_path = "/gpfs/scratch/ehpc543/FineVisionMax/full/"
seq_len = 4096

start_idx = 0
end_idx = 999