[model]
model_name = "Qwen/Qwen3-1.7B"

train_llm = true

[wandb]
run_name = "fourth iter"
project_name = "text_cat"
entity_name = "bsc_runs"

[training]
model_dir =  "/gpfs/scratch/ehpc391/cache/qwen3_1_7b/"
output_dir = "/gpfs/scratch/ehpc543/qwen_finetune/text_catalan"

load_text_model = false

total_steps = 10_000
tpi_multiplier = 2.0
save_steps = 1000

scheduler_type = "cosine"
warmup_steps = 200
min_lr_ratio = 0.1

lr_llm = 0.00002

data_parallel = 'ddp'
tp_size = 1
compile = false

resume = false
random_init_mlp = true

[data]
data_path = "/gpfs/scratch/ehpc543/FineVisionMax/full/"
seq_len = 8192

start_idx = 6000
end_idx = 9999