[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"

train_llm = false
train_vit = false
train_mlp = true

[wandb]
run_name = "test fixes"
project_name = "test_llavarecap"
entity_name = "bsc_runs"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen3_2b"
output_dir = "/data/151-1/users/shared_cache/qwen_finetune/test_fixes_llavarecap"

text_model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen3_1_7b_base"
load_text_model = true

vision_model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/siglip2_large"
load_vision_model = true

save_steps = 510
total_steps = 512

warmup_steps = 10

tp_size = 1
data_parallel = 'ddp'

tpi_multiplier = 3

scheduler_type = "cosine"

lr_llm = 2e-6
lr_mlp = 1e-3

compile = true

resume_checkpoint = false

[data]
data_path = "/data/151-1/datasets/llava_recap"
seq_len = 8192

packing_buffer_size = 1000

batch_size = 0
