[model]
model_name = "Qwen/Qwen3.5-6B-A3B"
model_impl = "native"

train_llm = true
train_mlp = true
train_vit = false

[wandb]
run_name = "moe"
project_name = "test"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen35_6b_a3b"
output_dir = "/data/151-1/users/shared_cache/qwen_finetune/checkpoints"

save_steps = 10000
total_steps = 10000
random_init = false

tp_size = 1
pp_size = 1
data_parallel = 'ddp'

ac_mode = "full"
compile = false

[data]
data_path = "/data/151-1/datasets/synth_test_datasets/cap_pretrain"
seq_len = 256

packing_buffer_size = 100

batch_size = 0
