[model]
model_name = "Qwen/Qwen3.5-2B"
model_impl = "native"

[wandb]
run_name = "no-tp"
project_name = "tp_debugging"
entity_name = "bsc_runs"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen35_2b"
output_dir = "/data/151-1/users/shared_cache/qwen_finetune/checkpoints"

save_steps = 10000
total_steps = 10000
random_init = false

scheduler_type = "cosine"

total_steps: int = 1_000
warmup_steps: int = 100
wsd_decay_ratio: float = 0.1
min_lr_ratio: float = 0.1

tp_size = 1
data_parallel = 'ddp'

compile = false

tpi_multiplier = 12

[data]
data_path = "/data/151-1/datasets/llava_recap"
seq_len = 8192

shuffle_buffer_size = 1000
packing_buffer_size = 1000
max_samples_per_sequence = 100

batch_size = 0
