[model]
model_name = "Qwen/Qwen3.5-2B"
model_impl = "native"

run_name = "TP=2 no-compile"
project_name = "qwen3.5 TP compile"
entity_name = "bsc_runs"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen35_2b"
output_dir = "/data/151-1/users/shared_cache/qwen_finetune/checkpoints"

save_steps = 10000
total_steps = 10000
random_init_mlp = false

tp_size = 2
data_parallel = 'ddp'

compile = true

[data]
data_path = "/data/151-1/datasets/synth_test_datasets/cap_pretrain"
seq_len = 2048

batch_size = 8
