[model]
model_name = "Qwen/Qwen3.5-2B"
model_impl = "native"

run_name = "vision cu_seqlens on dataloading"
project_name = "qwen3.5 improve compile"
entity_name = "bsc_runs"

[training]
model_dir = "/data/151-1/users/tockier/qwen_finetune/cache/qwen35_2b"
output_dir = "/data/151-1/users/shared_cache/qwen_finetune/checkpoints"

random_init_mlp = false

save_steps = 1000
total_steps = 10_000

scheduler_type = "cosine"
warmup_steps = 0
min_lr_ratio = 0.1

tp_size = 1
data_parallel = 'ddp'

compile = true

[data]
data_path = "/data/151-1/datasets/synth_test_datasets/cap_pretrain"
seq_len = 2048

batch_size = 8
