[model]
model_name = "Qwen/Qwen3.5-27B"
model_impl = "native"

train_llm = true
train_mlp = true
train_vit = false

[wandb]
run_name = "test 27b"
project_name = "scaling_27b"
entity_name = "bsc_runs"

[training]
model_dir = "/e/project1/reformo/ockier1/qwen_models/qwen3_5_27b"
output_dir = "/e/scratch/reformo/ockier1/checkpoints/test_35_27b"

tpi_multiplier = 1.0
save_steps = 1000

scheduler_type = "cosine"
total_steps = 18000
warmup_steps = 100
#wsd_decay_ratio = 0.1
min_lr_ratio = 0.1

lr_llm = 0.00002
lr_mlp = 0.0001

data_parallel = 'fsdp'

pp_size = 4
tp_size = 1

resume_checkpoint = false
random_init = false

ac_mode = 'full'

compile = false
async_tp = false

[data]
data_path = "/e/data1/datasets/products/llava_onevision_mid_training_85m/imagenet/EN"

packing_buffer_size = 115

seq_len = 6144
batch_size = 0
