[model]
model_name = "Qwen/Qwen3.5-2B"

model_impl = "native"

train_llm = true
train_mlp = true
train_vit = false

[wandb]
run_name = "bench_2b_64"
project_name = "scale_jupiter"
entity_name = "bsc_runs"

[training]
model_dir = "/e/project1/reformo/ockier1/qwen_models/qwen3_5_2b"
output_dir = "/e/scratch/reformo/ockier1/checkpoints/test_35_2b"

tpi_multiplier = 1.0
save_steps = 1000

scheduler_type = "cosine"
total_steps = 18000
warmup_steps = 100
#wsd_decay_ratio = 0.1
min_lr_ratio = 0.1

lr_llm = 0.00002
lr_mlp = 0.0001

data_parallel = 'fsdp'
tp_size = 1

resume_checkpoint = false
random_init_mlp = false

compile = false

[data]
data_path = "/e/project1/jureap59/ockier1/datasets/cap_pretrain"

seq_len = 8192

shuffle_buffer_size = 1000
packing_buffer_size = 1000
max_samples_per_sequence = 100

batch_size = 0

