[model]
model_name = "Qwen/Qwen3-VL-2B-Instruct"

train_llm = true
train_mlp = true
train_vit = false

[wandb]
run_name = "wsd_stable_finevision"
project_name = "mn5_onevision"
entity_name = "bsc_runs"

[training]
model_dir = "/gpfs/scratch/ehpc543/qwen_finetune/mid_training_test_3/models/step-8293"
output_dir = "/gpfs/scratch/ehpc543/qwen_finetune/instruct_wsd_finevision"

text_model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/qwen3_1_7b_base"
load_text_model = false
random_init = false

vision_model_dir = "/gpfs/scratch/ehpc543/tockier/qwen_models/siglip2_large"
load_vision_model = false

save_steps = 1000
total_steps = 23936

scheduler_type = "wsd"
warmup_steps = 500
wsd_decay_steps = 1000

lr_llm = 2e-6
lr_mlp = 1e-5
lr_vit = 1e-5

data_parallel = 'ddp'
tp_size = 1

tpi_multiplier = 1
compile = true

ac_memory_budget = 0.0
clear_cache_vram = 50
debug_batch_stats = false

resume_checkpoint = true

[data]
data_path = "/gpfs/scratch/ehpc543/finevision_energon"
seq_len = 6144

save_dataloader_state = true
restore_dataloader_state = false

packing_buffer_size = 1000
batch_size = 0

repeat = true