[model]
model_name = "Qwen/Qwen3-VL-4B-Instruct"

run_name = "test_2b"
project_name = "test_151_qwen_vl"

[training]
cache_dir = "/data/users/tockier/qwen_finetune/cache"
output_dir = "/data/users/tockier/qwen_finetune/checkpoints"
tpi_multiplier = 1.0

save_steps = 1000
scheduler_steps = 1000
random_init_mlp = false

sharding_strategy = 'ddp'

[data]
data_path = "/data-net/storage2/datasets/FineVisionMax/full/"
seq_len = 2048

start_idx = 0
end_idx = 3