[model]
model_name = "Qwen/Qwen3-VL-8B-Instruct"
run_name = "test_8B_quad_node"
project_name = "bsc_8b"
entity_name = "bsc_runs"

[training]
cache_dir = "/gpfs/scratch/ehpc391/qwens/qwen3_8b/"
output_dir = "/gpfs/scratch/ehpc391/qwen_finetune/test_2b/"
tpi_multiplier = 1.0
save_steps = 500

resume = false

# faster
split_vit_attn = false

data_parallel = 'fsdp'
tp_size = 2

[data]
data_path = "/gpfs/scratch/ehpc543/FineVisionMax/full/"
seq_len = 6144

start_idx = 0
end_idx = 999